In [164]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

data3 = pd.read_csv("Best Copy of Energy Data for CS ML 2000-2022 - Sheet1.csv")
future_data3 = pd.read_csv("Best Copy of Energy Data for CS ML 2000-2022 - Sheet1.csv")
data3.head()

,country,year,tes_coal,tes_natural_gas,tes_hydro,tes_nucelar,tes_solar_wind_otr,tes_biofuels,tes_oil,tfc_coal,...,elec_gen_solar,elec_gen_wind,elec_gen_solar_thermal,elec_gen_geothermal,elec_gen_sol/geothermal,elec_gen_tide,elec_gen_other,elec_consumption_total,co2_emissions_per_capita,gdp_per_capita
0,Australia,2000,2015828,806999,58896,0,3763,210841,1429894,175846,...,38,58,0,0,0,0,0,195.244,17.585955,45979.07657
1,Australia,2001,2018544,850415,59626,0,4531,212965,1281399,165416,...,44,210,0,0,0,0,0,206.484,17.690257,46314.62353
2,Australia,2002,2034808,788516,57157,0,5161,226713,1360752,125943,...,50,364,0,0,0,0,0,211.730,17.892464,47599.40793
3,Australia,2003,2015734,856586,58586,0,5521,219530,1480641,144840,...,58,703,1,0,1,0,0,207.548,17.665647,48509.66322
4,Australia,2004,2089200,859874,57996,0,5404,216460,1488010,151394,...,68,705,1,0,1,0,0,212.475,18.149135,50018.59045

In [165]:
data3["country_code"] = data3["country"].astype("category").cat.codes
future_data3["country_code"] = future_data3["country"].astype("category").cat.codes

In [166]:
data3["renew/sus_elec_gen"] = data3["elec_gen_solar"] + data3["elec_gen_wind"] + data3["elec_gen_hydro/tide"] + data3["elec_gen_sol/geothermal"]
future_data3["renew/sus_elec_gen"] = future_data3["elec_gen_solar"] + future_data3["elec_gen_wind"] + future_data3["elec_gen_hydro/tide"] + future_data3["elec_gen_sol/geothermal"]

In [167]:
data3["elec_gen_total"] = data3["renew/sus_elec_gen"] + data3["elec_gen_oil"] + data3["elec_gen_coal"] + data3["elec_gen_biofuels"] + data3["elec_gen_natural_gas"] + data3["elec_gen_nuclear"] + data3["elec_gen_other"] + data3["elec_gen_waste"]
future_data3["elec_gen_total"] = future_data3["renew/sus_elec_gen"] + future_data3["elec_gen_oil"] + future_data3["elec_gen_coal"] + future_data3["elec_gen_biofuels"] + future_data3["elec_gen_natural_gas"] + future_data3["elec_gen_nuclear"] + future_data3["elec_gen_other"] + future_data3["elec_gen_waste"]

In [168]:
data3["true_renew_share"] = data3["renew/sus_elec_gen"] / data3["elec_gen_total"]
future_data3["true_renew_share"] = future_data3["renew/sus_elec_gen"] / future_data3["elec_gen_total"]

In [169]:
data3["renew_share_change"] = data3.groupby("country_code")["true_renew_share"].diff()
future_data3["renew_share_change"] = future_data3.groupby("country_code")["true_renew_share"].diff()

In [170]:
future_data3

,country,year,tes_coal,tes_natural_gas,tes_hydro,tes_nucelar,tes_solar_wind_otr,tes_biofuels,tes_oil,tfc_coal,...,elec_gen_tide,elec_gen_other,elec_consumption_total,co2_emissions_per_capita,gdp_per_capita,country_code,renew/sus_elec_gen,elec_gen_total,true_renew_share,renew_share_change
0,Australia,2000,2015828,806999,58896,0,3763,210841,1429894,175846,...,0,0,195.244,17.585955,45979.07657,0,16816,210224,0.079991,NaN
1,Australia,2001,2018544,850415,59626,0,4531,212965,1281399,165416,...,0,0,206.484,17.690257,46314.62353,0,17187,224635,0.076511,-0.003480
2,Australia,2002,2034808,788516,57157,0,5161,226713,1360752,125943,...,0,0,211.730,17.892464,47599.40793,0,16468,227555,0.072369,-0.004141
3,Australia,2003,2015734,856586,58586,0,5521,219530,1480641,144840,...,0,0,207.548,17.665647,48509.66322,0,17252,220802,0.078133,0.005764
4,Australia,2004,2089200,859874,57996,0,5404,216460,1488010,151394,...,0,0,212.475,18.149135,50018.59045,0,17105,228434,0.074879,-0.003254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,United States,2018,13426291,29054726,1063803,9178130,1841813,4393036,33566263,701165,...,0,5272,4288.759,14.934503,59526.66570,38,696795,4455434,0.156392,-0.000398
893,United States,2019,11510279,31078534,1043274,9199964,1934725,4445624,33293509,644740,...,0,5074,4186.693,14.355887,60750.98986,38,724610,4391756,0.164993,0.008601
894,United States,2020,9280479,30104803,1033702,8979813,2180848,4108850,29400955,540438,...,0,4865,4109.389,12.830346,59194.66652,38,788187,4260036,0.185019,0.020026
895,United States,2021,10635146,30274618,912523,8853288,2455808,4383684,31968560,567856,...,0,4687,4169.876,13.681768,62680.25036,38,827308,4374671,0.189113,0.004094
896,United States,2022,10016167,32292088,923764,8767293,2798738,4395527,31721656,553349,...,0,4482,4331.591,13.779831,63886.13171,38,924549,4495362,0.205667,0.016554

In [171]:
data3

,country,year,tes_coal,tes_natural_gas,tes_hydro,tes_nucelar,tes_solar_wind_otr,tes_biofuels,tes_oil,tfc_coal,...,elec_gen_tide,elec_gen_other,elec_consumption_total,co2_emissions_per_capita,gdp_per_capita,country_code,renew/sus_elec_gen,elec_gen_total,true_renew_share,renew_share_change
0,Australia,2000,2015828,806999,58896,0,3763,210841,1429894,175846,...,0,0,195.244,17.585955,45979.07657,0,16816,210224,0.079991,NaN
1,Australia,2001,2018544,850415,59626,0,4531,212965,1281399,165416,...,0,0,206.484,17.690257,46314.62353,0,17187,224635,0.076511,-0.003480
2,Australia,2002,2034808,788516,57157,0,5161,226713,1360752,125943,...,0,0,211.730,17.892464,47599.40793,0,16468,227555,0.072369,-0.004141
3,Australia,2003,2015734,856586,58586,0,5521,219530,1480641,144840,...,0,0,207.548,17.665647,48509.66322,0,17252,220802,0.078133,0.005764
4,Australia,2004,2089200,859874,57996,0,5404,216460,1488010,151394,...,0,0,212.475,18.149135,50018.59045,0,17105,228434,0.074879,-0.003254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
892,United States,2018,13426291,29054726,1063803,9178130,1841813,4393036,33566263,701165,...,0,5272,4288.759,14.934503,59526.66570,38,696795,4455434,0.156392,-0.000398
893,United States,2019,11510279,31078534,1043274,9199964,1934725,4445624,33293509,644740,...,0,5074,4186.693,14.355887,60750.98986,38,724610,4391756,0.164993,0.008601
894,United States,2020,9280479,30104803,1033702,8979813,2180848,4108850,29400955,540438,...,0,4865,4109.389,12.830346,59194.66652,38,788187,4260036,0.185019,0.020026
895,United States,2021,10635146,30274618,912523,8853288,2455808,4383684,31968560,567856,...,0,4687,4169.876,13.681768,62680.25036,38,827308,4374671,0.189113,0.004094
896,United States,2022,10016167,32292088,923764,8767293,2798738,4395527,31721656,553349,...,0,4482,4331.591,13.779831,63886.13171,38,924549,4495362,0.205667,0.016554

In [172]:
data3["renew_share_next"] = data3.groupby("country_code")["true_renew_share"].shift(-1)

In [173]:
data3 = data3.dropna(subset=["renew_share_next"])
data3

,country,year,tes_coal,tes_natural_gas,tes_hydro,tes_nucelar,tes_solar_wind_otr,tes_biofuels,tes_oil,tfc_coal,...,elec_gen_other,elec_consumption_total,co2_emissions_per_capita,gdp_per_capita,country_code,renew/sus_elec_gen,elec_gen_total,true_renew_share,renew_share_change,renew_share_next
0,Australia,2000,2015828,806999,58896,0,3763,210841,1429894,175846,...,0,195.244,17.585955,45979.07657,0,16816,210224,0.079991,NaN,0.076511
1,Australia,2001,2018544,850415,59626,0,4531,212965,1281399,165416,...,0,206.484,17.690257,46314.62353,0,17187,224635,0.076511,-0.003480,0.072369
2,Australia,2002,2034808,788516,57157,0,5161,226713,1360752,125943,...,0,211.730,17.892464,47599.40793,0,16468,227555,0.072369,-0.004141,0.078133
3,Australia,2003,2015734,856586,58586,0,5521,219530,1480641,144840,...,0,207.548,17.665647,48509.66322,0,17252,220802,0.078133,0.005764,0.074879
4,Australia,2004,2089200,859874,57996,0,5404,216460,1488010,151394,...,0,212.475,18.149135,50018.59045,0,17105,228434,0.074879,-0.003254,0.072495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,United States,2017,13847655,26960229,1088504,9151214,1661988,4126342,33087374,712304,...,5443,4116.629,14.566783,58151.70214,38,672067,4286422,0.156790,0.020164,0.156392
892,United States,2018,13426291,29054726,1063803,9178130,1841813,4393036,33566263,701165,...,5272,4288.759,14.934503,59526.66570,38,696795,4455434,0.156392,-0.000398,0.164993
893,United States,2019,11510279,31078534,1043274,9199964,1934725,4445624,33293509,644740,...,5074,4186.693,14.355887,60750.98986,38,724610,4391756,0.164993,0.008601,0.185019
894,United States,2020,9280479,30104803,1033702,8979813,2180848,4108850,29400955,540438,...,4865,4109.389,12.830346,59194.66652,38,788187,4260036,0.185019,0.020026,0.189113
895,United States,2021,10635146,30274618,912523,8853288,2455808,4383684,31968560,567856,...,4687,4169.876,13.681768,62680.25036,38,827308,4374671,0.189113,0.004094,0.205667

In [174]:
y3 = data3["renew_share_next"]
y3

0      0.076511
1      0.072369
2      0.078133
3      0.074879
4      0.072495
         ...
891    0.156392
892    0.164993
893    0.185019
894    0.189113
895    0.205667
Name: renew_share_next, Length: 858, dtype: float64

In [175]:
X3 = data3.drop(columns=["true_renew_share", "renew_share_next", "country", "co2_emissions_total", "elec_gen_hydro", "elec_gen_tide", "elec_gen_geothermal",
                              "elec_gen_solar_thermal", "elec_gen_sol/geothermal", "elec_gen_hydro/tide", "elec_gen_solar", "elec_gen_wind", "elec_gen_total", "renew/sus_elec_gen",
                              "co2_emissions_coal", "co2_emissions_oil", "co2_emissions_natural_gas", "co2_emissions_other", "co2_emissions_elec_gen_incl_chp", 
                              "elec_gen_coal", "elec_gen_oil", "elec_gen_natural_gas", "elec_gen_biofuels", "elec_gen_waste", "elec_gen_nuclear", "elec_gen_other", "country_code"])
X3

,year,tes_coal,tes_natural_gas,tes_hydro,tes_nucelar,tes_solar_wind_otr,tes_biofuels,tes_oil,tfc_coal,tfc_oil,tfc_natural_gas,tfc_solar_wind,tfc_biofuels,tfc_electricity,tfc_heat,elec_consumption_total,co2_emissions_per_capita,gdp_per_capita,renew_share_change
0,2000,2015828,806999,58896,0,3763,210841,1429894,175846,1453500,476844,3417,181752,621896,0,195.244,17.585955,45979.07657,NaN
1,2001,2018544,850415,59626,0,4531,212965,1281399,165416,1438847,503116,3617,180038,649432,0,206.484,17.690257,46314.62353,-0.003480
2,2002,2034808,788516,57157,0,5161,226713,1360752,125943,1417203,494640,3670,190811,688021,0,211.730,17.892464,47599.40793,-0.004141
3,2003,2015734,856586,58586,0,5521,219530,1480641,144840,1479100,529306,2775,145331,665769,0,207.548,17.665647,48509.66322,0.005764
4,2004,2089200,859874,57996,0,5404,216460,1488010,151394,1525625,539122,2616,137087,681541,0,212.475,18.149135,50018.59045,-0.003254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
891,2017,13847655,26960229,1088504,9151214,1661988,4126342,33087374,712304,31115924,14499416,88557,3237927,13522015,245406,4116.629,14.566783,58151.70214,0.020164
892,2018,13426291,29054726,1063803,9178130,1841813,4393036,33566263,701165,31739161,15934768,148035,3503246,14043151,260320,4288.759,14.934503,59526.66570,-0.000398
893,2019,11510279,31078534,1043274,9199964,1934725,4445624,33293509,644740,31622507,16018751,127018,3590849,13787827,252619,4186.693,14.355887,60750.98986,0.008601
894,2020,9280479,30104803,1033702,8979813,2180848,4108850,29400955,540438,27963136,14924938,128891,3294752,13600044,249865,4109.389,12.830346,59194.66652,0.020026
895,2021,10635146,30274618,912523,8853288,2455808,4383684,31968560,567856,30340529,15475637,136878,3484833,13817551,235115,4169.876,13.681768,62680.25036,0.004094

In [176]:
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split

X3_columns = X3.columns

train = data3[data3["year"] <= 2018]
test = data3[data3["year"] > 2018]

X3_train = train[X3_columns]
y3_train = train["renew_share_next"]

X3_test = test[X3_columns]
y3_test = test["renew_share_next"]

RF_model3 = RandomForestRegressor(n_estimators=200, random_state=42)
RF_model3.fit(X3_train, y3_train)

RandomForestRegressor(n_estimators=200, random_state=42)

In [177]:
X3_train

,year,tes_coal,tes_natural_gas,tes_hydro,tes_nucelar,tes_solar_wind_otr,tes_biofuels,tes_oil,tfc_coal,tfc_oil,tfc_natural_gas,tfc_solar_wind,tfc_biofuels,tfc_electricity,tfc_heat,elec_consumption_total,co2_emissions_per_capita,gdp_per_capita,renew_share_change
0,2000,2015828,806999,58896,0,3763,210841,1429894,175846,1453500,476844,3417,181752,621896,0,195.244,17.585955,45979.07657,NaN
1,2001,2018544,850415,59626,0,4531,212965,1281399,165416,1438847,503116,3617,180038,649432,0,206.484,17.690257,46314.62353,-0.003480
2,2002,2034808,788516,57157,0,5161,226713,1360752,125943,1417203,494640,3670,190811,688021,0,211.730,17.892464,47599.40793,-0.004141
3,2003,2015734,856586,58586,0,5521,219530,1480641,144840,1479100,529306,2775,145331,665769,0,207.548,17.665647,48509.66322,0.005764
4,2004,2089200,859874,57996,0,5404,216460,1488010,151394,1525625,539122,2616,137087,681541,0,212.475,18.149135,50018.59045,-0.003254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,2014,18072073,26276307,941302,9060916,1236979,4292757,32367234,929619,30246807,14733581,103741,3315329,13640234,234204,4138.262,15.790183,55394.45104,0.002735
889,2015,15660181,27067980,903664,9057687,1312775,4183390,33056355,817007,30883847,14113039,107120,3228030,13611009,228511,4128.507,15.300856,56572.91890,0.002621
890,2016,14300841,27334911,970812,9162741,1491265,4152602,32837869,732802,31040556,14167626,94308,3263132,13730187,277588,4153.733,14.905542,57151.47084,0.016528
891,2017,13847655,26960229,1088504,9151214,1661988,4126342,33087374,712304,31115924,14499416,88557,3237927,13522015,245406,4116.629,14.566783,58151.70214,0.020164
892,2018,13426291,29054726,1063803,9178130,1841813,4393036,33566263,701165,31739161,15934768,148035,3503246,14043151,260320,4288.759,14.934503,59526.66570,-0.000398

In [178]:
y3_train

0      0.076511
1      0.072369
2      0.078133
3      0.074879
4      0.072495
         ...
888    0.120098
889    0.136626
890    0.156790
891    0.156392
892    0.164993
Name: renew_share_next, Length: 741, dtype: float64

In [179]:
y3_rf_train_pred = RF_model3.predict(X3_train)
y3_rf_test_pred = RF_model3.predict(X3_test)

In [180]:
from sklearn.metrics import mean_squared_error, r2_score

rf3_train_mse = mean_squared_error(y3_train, y3_rf_train_pred)
rf3_train_r2 = r2_score(y3_train, y3_rf_train_pred)

rf3_test_mse = mean_squared_error(y3_test, y3_rf_test_pred)
rf3_test_r2 = r2_score(y3_test, y3_rf_test_pred)

In [181]:
rf3_results = pd.DataFrame(["Random Forest Regressor", rf3_train_mse, rf3_train_r2, rf3_test_mse, rf3_test_r2]).transpose()
rf3_results.columns = ["Method", "Training MSE", "Training R2", "Testing MSE", "Testing R2"]
rf3_results

                    Method Training MSE Training R2 Testing MSE Testing R2
0  Random Forest Regressor     0.000297    0.995025    0.003966   0.926513

In [182]:
import pandas as pd

importance3 = RF_model3.feature_importances_

feature_importance3 = pd.Series(importance3, index=X3.columns)
print(feature_importance3.sort_values(ascending=False))

tes_hydro                   0.325660
tes_coal                    0.278097
tes_natural_gas             0.062278
gdp_per_capita              0.060787
tfc_natural_gas             0.047262
tfc_coal                    0.028032
co2_emissions_per_capita    0.027225
tes_solar_wind_otr          0.021608
elec_consumption_total      0.020618
tfc_solar_wind              0.020319
tes_oil                     0.017226
tfc_electricity             0.016843
tfc_heat                    0.015126
tes_biofuels                0.014698
tfc_oil                     0.012940
renew_share_change          0.011674
tfc_biofuels                0.008916
year                        0.006614
tes_nucelar                 0.004077
dtype: float64

In [183]:
future_data3 = future_data3[future_data3["year"] == 2022].copy()

X3_future = future_data3[X3_columns]
X3_future

future_data3["pred_2023"] = RF_model3.predict(X3_future)

In [184]:
future_2023 = future_data3.copy()

future_2023["year"] = 2023

future_2023["true_renew_share"] = future_data3["pred_2023"]
future_2023["renew_share_change"] = future_2023["true_renew_share"] - future_data3["true_renew_share"]

X_future_2023 = future_2023[X3_columns]

future_2023["pred_2024"] = RF_model3.predict(X_future_2023)

In [185]:
future_data3[["country", "true_renew_share", "pred_2023"]].head()

        country  true_renew_share  pred_2023
22   Australia           0.297586   0.206226
45     Austria           0.725035   0.602106
68      Belgium          0.217577   0.170210
91       Brazil          0.795535   0.682289
114      Canada          0.672674   0.611649

In [186]:
future_2023[["country", "true_renew_share", "pred_2024"]].head()

        country  true_renew_share  pred_2024
22   Australia           0.206226   0.221721
45     Austria           0.602106   0.601743
68      Belgium          0.170210   0.143756
91       Brazil          0.682289   0.686683
114      Canada          0.611649   0.611800

In [187]:
future_2024 = future_2023.copy()

future_2024["year"] = 2024

future_2024["true_renew_share"] = future_2023["pred_2024"]
future_2024["renew_share_change"] = future_2024["true_renew_share"] - future_2023["true_renew_share"]

X_future_2024 = future_2024[X3_columns]

future_2024["pred_2025"] = RF_model3.predict(X_future_2024)

In [190]:
future_2025 = future_2024.copy()

future_2025["year"] = 2025

future_2025["true_renew_share"] = future_2024["pred_2025"]
future_2025["renew_share_change"] = future_2025["true_renew_share"] - future_2024["true_renew_share"]

X_future_2025 = future_2025[X3_columns]

future_2025["pred_2026"] = RF_model3.predict(X_future_2025)

In [191]:
future_2026 = future_2025.copy()

future_2026["year"] = 2026

future_2026["true_renew_share"] = future_2025["pred_2026"]
future_2026["renew_share_change"] = future_2026["true_renew_share"] - future_2025["true_renew_share"]

X_future_2026 = future_2026[X3_columns]

future_2026["pred_2027"] = RF_model3.predict(X_future_2026)

In [192]:
future_2027 = future_2026.copy()

future_2027["year"] = 2027

future_2027["true_renew_share"] = future_2026["pred_2027"]
future_2027["renew_share_change"] = future_2027["true_renew_share"] - future_2026["true_renew_share"]

X_future_2027 = future_2027[X3_columns]

future_2027["pred_2028"] = RF_model3.predict(X_future_2027)

In [193]:
future_2028 = future_2027.copy()

future_2028["year"] = 2028

future_2028["true_renew_share"] = future_2027["pred_2028"]
future_2028["renew_share_change"] = future_2028["true_renew_share"] - future_2027["true_renew_share"]

X_future_2028 = future_2028[X3_columns]

future_2028["pred_2029"] = RF_model3.predict(X_future_2028)

In [196]:
future_2029 = future_2028.copy()

future_2029["year"] = 2029

future_2029["true_renew_share"] = future_2028["pred_2029"]
future_2029["renew_share_change"] = future_2029["true_renew_share"] - future_2028["true_renew_share"]

X_future_2029 = future_2029[X3_columns]

future_2029["pred_2030"] = RF_model3.predict(X_future_2029)

In [197]:
future_2030 = future_2029.copy()

future_2030["year"] = 2030

future_2030["true_renew_share"] = future_2029["pred_2030"]
future_2030["renew_share_change"] = future_2030["true_renew_share"] - future_2029["true_renew_share"]

X_future_2030 = future_2030[X3_columns]

future_2030["pred_2029"] = RF_model3.predict(X_future_2030)